# Generated by Django 5.2.6 on 2025-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
